/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.monsterbrain.ui;

import com.monsterbrain.main.MainContentJFrame;
import com.monsterbrain.model.ProjectModel;
import com.monsterbrain.utils.Constants;
import com.monsterbrain.utils.SaveFileUtils;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.function.Function;
import javax.swing.border.TitledBorder;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Faisal Rasak
 */
public class ProjectJPanel extends javax.swing.JPanel {

    private final Function<String, Void> callbackFn;
    private ProjectModel projectInfo;

    /**
     * Creates new form ProjectJPanel
     *
     * @param model
     * @param callback
     */
    public ProjectJPanel(ProjectModel model, Function<String, Void> callback) {
        this.callbackFn = callback;
        projectInfo = model;
        initComponents();
        updateTitle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpenFolder = new javax.swing.JButton();
        btnOpenSrcFolder = new javax.swing.JButton();
        btnOpenBuildFolder = new javax.swing.JButton();
        btnOpenInStudio = new javax.swing.JButton();
        btnDeleteProject = new javax.swing.JButton();
        projectTitleLabel = new javax.swing.JLabel();
        btnEditTitle = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOpenFolder.setText("Open Folder");
        btnOpenFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFolderActionPerformed(evt);
            }
        });

        btnOpenSrcFolder.setText("Src Folder");
        btnOpenSrcFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenSrcFolderActionPerformed(evt);
            }
        });

        btnOpenBuildFolder.setText("Build Folder");
        btnOpenBuildFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenBuildFolderActionPerformed(evt);
            }
        });

        btnOpenInStudio.setText("Open in Android Studio");
        btnOpenInStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenInStudioActionPerformed(evt);
            }
        });

        btnDeleteProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/monsterbrain/assets/ic_delete.png"))); // NOI18N
        btnDeleteProject.setToolTipText("delete project");
        btnDeleteProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProjectActionPerformed(evt);
            }
        });

        projectTitleLabel.setText("Awesome Project");

        btnEditTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/monsterbrain/assets/ic_edit.png"))); // NOI18N
        btnEditTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOpenFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenSrcFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenBuildFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(projectTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteProject, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOpenInStudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditTitle)
                    .addComponent(btnDeleteProject, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpenInStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenFolder)
                    .addComponent(btnOpenSrcFolder)
                    .addComponent(btnOpenBuildFolder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFolderActionPerformed
        callbackFn.apply(Constants.ACTION_OPEN_PROJECT_FOLDER);

        try {
            Desktop.getDesktop().open(new File(projectInfo.getLocation()));
        } catch (IOException ex) {
            Logger.getLogger(ProjectJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOpenFolderActionPerformed

    private void btnOpenSrcFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenSrcFolderActionPerformed
        callbackFn.apply(Constants.ACTION_OPEN_SRC_FOLDER);

        File srcFolder = new File(projectInfo.getLocation() + File.separator + "app" + File.separator + "src");
        if (srcFolder.exists()) {
            try {
                Desktop.getDesktop().open(srcFolder);
            } catch (IOException ex) {
                Logger.getLogger(ProjectJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenSrcFolderActionPerformed

    private void btnOpenBuildFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenBuildFolderActionPerformed
        callbackFn.apply(Constants.ACTION_OPEN_BUILD_FOLDER);
        
        File buildFolder = new File(projectInfo.getLocation() + File.separator + "app" + File.separator + "build");
        if (buildFolder.exists()) {
            try {
                Desktop.getDesktop().open(buildFolder);
            } catch (IOException ex) {
                Logger.getLogger(ProjectJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenBuildFolderActionPerformed

    private void btnOpenInStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenInStudioActionPerformed
        String studioPath = SaveFileUtils.instance().getProgramConfig().getAndroidStudioPath();
        
        ProcessBuilder builder = new ProcessBuilder(
                "cmd.exe", "/c", "\"" + studioPath + "\" " + projectInfo.getLocation());
        builder.redirectErrorStream(true);
        Process p;
        try {
            p = builder.start();
            /*BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String line;
            while (true) {
                line = reader.readLine();
                if (line == null) {
                    break;
                }
                System.out.println(line);
            }*/
        } catch (IOException ex) {
            Logger.getLogger(ProjectJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOpenInStudioActionPerformed

    private void btnDeleteProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProjectActionPerformed
        int option = JOptionPane.showConfirmDialog(this.getRootPane(), "Do you want to delete the project ?");
        System.out.println("option = " + option);
        if (option == JOptionPane.YES_OPTION) {
            SaveFileUtils.instance().deleteProject(projectInfo);
            JOptionPane.showMessageDialog(this.getRootPane(), "Project deleted successfully. Please restart app to see changes :) ");
        }
    }//GEN-LAST:event_btnDeleteProjectActionPerformed

    private void btnEditTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditTitleActionPerformed
        String name = JOptionPane.showInputDialog("Enter a new Project Name (previous name: "+projectInfo.getDisplayName()+")");
        System.out.println("name = " + name);
        if (name != null && !name.isEmpty()) {
            SaveFileUtils.instance().setNewDisplayName(projectInfo, name);
            updateTitle();
        }
    }//GEN-LAST:event_btnEditTitleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteProject;
    private javax.swing.JButton btnEditTitle;
    private javax.swing.JButton btnOpenBuildFolder;
    private javax.swing.JButton btnOpenFolder;
    private javax.swing.JButton btnOpenInStudio;
    private javax.swing.JButton btnOpenSrcFolder;
    private javax.swing.JLabel projectTitleLabel;
    // End of variables declaration//GEN-END:variables

    private void updateTitle() {
        // set project title
        if (getBorder() instanceof TitledBorder) {
            ((TitledBorder) getBorder()).setTitle(projectInfo.getDisplayName());
        }
        
        projectTitleLabel.setText(projectInfo.getDisplayName());
    }
}
