/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.monsterbrain.ui;

import com.monsterbrain.model.ProjectModel;
import com.monsterbrain.utils.Constants;
import com.monsterbrain.utils.SaveFileUtils;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.function.Function;
import javax.swing.border.TitledBorder;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Faisal Rasak
 */
public class ProjectJPanel extends javax.swing.JPanel {

    private final Function<String, Void> callbackFn;
    private ProjectModel projectInfo;

    /**
     * Creates new form ProjectJPanel
     *
     * @param model
     * @param callback
     */
    public ProjectJPanel(ProjectModel model, Function<String, Void> callback) {
        this.callbackFn = callback;
        projectInfo = model;
        initComponents();
        showDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpenFolder = new javax.swing.JButton();
        btnOpenSrcFolder = new javax.swing.JButton();
        btnOpenBuildFolder = new javax.swing.JButton();
        btnOpenInStudio = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Project Title"));

        btnOpenFolder.setText("Open Folder");
        btnOpenFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFolderActionPerformed(evt);
            }
        });

        btnOpenSrcFolder.setText("Src Folder");
        btnOpenSrcFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenSrcFolderActionPerformed(evt);
            }
        });

        btnOpenBuildFolder.setText("Build Folder");
        btnOpenBuildFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenBuildFolderActionPerformed(evt);
            }
        });

        btnOpenInStudio.setText("Open in Android Studio");
        btnOpenInStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenInStudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpenInStudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenSrcFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenBuildFolder)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnOpenInStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpenFolder)
                    .addComponent(btnOpenSrcFolder)
                    .addComponent(btnOpenBuildFolder))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFolderActionPerformed
        callbackFn.apply(Constants.ACTION_OPEN_PROJECT_FOLDER);

        try {
            Desktop.getDesktop().open(new File(projectInfo.getLocation()));
        } catch (IOException ex) {
            Logger.getLogger(ProjectJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOpenFolderActionPerformed

    private void btnOpenSrcFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenSrcFolderActionPerformed
        callbackFn.apply(Constants.ACTION_OPEN_SRC_FOLDER);

        File srcFolder = new File(projectInfo.getLocation() + File.separator + "app" + File.separator + "src");
        if (srcFolder.exists()) {
            try {
                Desktop.getDesktop().open(srcFolder);
            } catch (IOException ex) {
                Logger.getLogger(ProjectJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenSrcFolderActionPerformed

    private void btnOpenBuildFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenBuildFolderActionPerformed
        callbackFn.apply(Constants.ACTION_OPEN_BUILD_FOLDER);
        
        File buildFolder = new File(projectInfo.getLocation() + File.separator + "app" + File.separator + "build");
        if (buildFolder.exists()) {
            try {
                Desktop.getDesktop().open(buildFolder);
            } catch (IOException ex) {
                Logger.getLogger(ProjectJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnOpenBuildFolderActionPerformed

    private void btnOpenInStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenInStudioActionPerformed
        String studioPath = SaveFileUtils.instance().getProgramConfig().getAndroidStudioPath();
        
        ProcessBuilder builder = new ProcessBuilder(
                "cmd.exe", "/c", "\"" + studioPath + "\" " + projectInfo.getLocation());
        builder.redirectErrorStream(true);
        Process p;
        try {
            p = builder.start();
            /*BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String line;
            while (true) {
                line = reader.readLine();
                if (line == null) {
                    break;
                }
                System.out.println(line);
            }*/
        } catch (IOException ex) {
            Logger.getLogger(ProjectJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOpenInStudioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenBuildFolder;
    private javax.swing.JButton btnOpenFolder;
    private javax.swing.JButton btnOpenInStudio;
    private javax.swing.JButton btnOpenSrcFolder;
    // End of variables declaration//GEN-END:variables

    private void showDetails() {
        // set project title
        if (getBorder() instanceof TitledBorder) {
            ((TitledBorder) getBorder()).setTitle(projectInfo.getDisplayName());
        }
    }
}
